### ISSUE TITLE
API=30 fails with `Failed to find package 'system-images;android-30`

### ISSUE THREAD

**Issue by hannesa2** [Malinskiy/action-android#47]
When I try to run tests with api30 I run into

```
Warning: Failed to find package 'system-images;android-30;default;x86_64'
Error: The process 'bash' failed with exit code 1
    at ExecState._setResult (/Users/runner/work/_actions/malinskiy/action-android/release/0.1.2/emulator-run-cmd/node_modules/@actions/exec/lib/toolrunner.js:548:25)
    at ExecState.CheckComplete (/Users/runner/work/_actions/malinskiy/action-android/release/0.1.2/emulator-run-cmd/node_modules/@actions/exec/lib/toolrunner.js:531:18)
Error: The process 'bash' failed with exit code 1
    at ChildProcess.<anonymous> (/Users/runner/work/_actions/malinskiy/action-android/release/0.1.2/emulator-run-cmd/node_modules/@actions/exec/lib/toolrunner.js:431:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
```

Please see complete job https://github.com/hannesa2/paho.mqtt.android/pull/194/checks?check_run_id=3289979571

**Comment by Malinskiy** [comment]
Hey @hannesa2 

Unfortunately Google doesn't provide android emulator API 30 without google-apis, that's why it fails with "default".

Hope this helps.

**Comment by hannesa2** [comment]
Good to know 👍

Thank you
